apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-page-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-page
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
      metadata:
        labels:
          app: error-page
          version: v2
      spec:
        containers:
          - image: tokers/error-page:latest
            imagePullPolicy: IfNotPresent
            name: error-page
            ports:
              - name: http
                protocol: TCP
                containerPort: 9011
            args:
              - v2
---
apiVersion: v1
kind: Service
metadata:
  name: error-page-v2
spec:
  selector:
    app: error-page
    version: v2
  ports:
    - port: 9011
      targetPort: 9011
      protocol: TCP
