apiVersion: v1
kind: ServiceAccount
metadata:
  name: canary-release-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canary-release-controller-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: canary-release-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: canary-release-controller-clusterrole
subjects:
  - kind: ServiceAccount
    name: canary-release-account
    namespace: canary-release-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-release-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-release-controller
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
      metadata:
        labels:
          app: canary-release-controller
      spec:
        serviceAccountName: canary-release-account
        containers:
          - image: tokers/canary-release-controller:latest
            imagePullPolicy: IfNotPresent
            name: canary-release-controller
            env:
              - name: API7_CLOUD_ADDR
                valueFrom:
                  secretKeyRef:
                    name: api7-cloud
                    key: addr
              - name: API7_CLOUD_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: api7-cloud
                    key: token
            ports:
              - name: http
                protocol: TCP
                containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: canary-release-controller
spec:
  selector:
    app: canary-release-controller
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
